name: gmc_website
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/isometrics/challenges.png
    - assets/isometrics/coaches.png
    - assets/isometrics/company.png
    - assets/isometrics/contact.png
    - assets/isometrics/creativity.png
    - assets/isometrics/cv.png
    - assets/isometrics/gmc_home_main.png
    - assets/isometrics/inspirationboard.png
    - assets/isometrics/knowledge.png
    - assets/isometrics/mission.png
    - assets/isometrics/network.png
    - assets/isometrics/personal_development.png
    - assets/isometrics/picture.png
    - assets/isometrics/story.png
    - assets/isometrics/team.png
    - assets/isometrics/whyus.png
    - assets/isometrics/wildcard.png
    - assets/logos/gmc.png
    - assets/logos/bidco.jpg
    - assets/logos/clarity4d.png
    - assets/logos/incentro.png
    - assets/logos/klm.png

  fonts:
     - family: Manjari
       fonts:
         - asset: assets/fonts/manjari.ttf
  
     - family: Open Sans
       fonts:
         - asset: assets/fonts/opensans.ttf